package com.wangzefeng.dao;

import com.wangzefeng.pojo.TestRecord;
import com.wangzefeng.example.TestRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int countByExample(TestRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int deleteByExample(TestRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int deleteByPrimaryKey(String testRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int insert(TestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int insertSelective(TestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    List<TestRecord> selectByExample(TestRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    TestRecord selectByPrimaryKey(String testRecordId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestRecord record, @Param("example") TestRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByExample(@Param("record") TestRecord record, @Param("example") TestRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByPrimaryKeySelective(TestRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByPrimaryKey(TestRecord record);
}