package com.wangzefeng.dao;

import com.wangzefeng.pojo.TestExamination;
import com.wangzefeng.example.TestExaminationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TestExaminationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int countByExample(TestExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int deleteByExample(TestExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int deleteByPrimaryKey(String testExaminationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int insert(TestExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int insertSelective(TestExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    List<TestExamination> selectByExample(TestExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    TestExamination selectByPrimaryKey(String testExaminationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByExampleSelective(@Param("record") TestExamination record, @Param("example") TestExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByExample(@Param("record") TestExamination record, @Param("example") TestExaminationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByPrimaryKeySelective(TestExamination record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    int updateByPrimaryKey(TestExamination record);
}