package com.wangzefeng.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestRecordExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public TestRecordExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTestRecordIdIsNull() {
            addCriterion("test_record_id is null");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdIsNotNull() {
            addCriterion("test_record_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdEqualTo(String value) {
            addCriterion("test_record_id =", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdNotEqualTo(String value) {
            addCriterion("test_record_id <>", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdGreaterThan(String value) {
            addCriterion("test_record_id >", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_record_id >=", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdLessThan(String value) {
            addCriterion("test_record_id <", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdLessThanOrEqualTo(String value) {
            addCriterion("test_record_id <=", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdLike(String value) {
            addCriterion("test_record_id like", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdNotLike(String value) {
            addCriterion("test_record_id not like", value, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdIn(List<String> values) {
            addCriterion("test_record_id in", values, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdNotIn(List<String> values) {
            addCriterion("test_record_id not in", values, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdBetween(String value1, String value2) {
            addCriterion("test_record_id between", value1, value2, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestRecordIdNotBetween(String value1, String value2) {
            addCriterion("test_record_id not between", value1, value2, "testRecordId");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNull() {
            addCriterion("test_time is null");
            return (Criteria) this;
        }

        public Criteria andTestTimeIsNotNull() {
            addCriterion("test_time is not null");
            return (Criteria) this;
        }

        public Criteria andTestTimeEqualTo(Date value) {
            addCriterion("test_time =", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotEqualTo(Date value) {
            addCriterion("test_time <>", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThan(Date value) {
            addCriterion("test_time >", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("test_time >=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThan(Date value) {
            addCriterion("test_time <", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeLessThanOrEqualTo(Date value) {
            addCriterion("test_time <=", value, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeIn(List<Date> values) {
            addCriterion("test_time in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotIn(List<Date> values) {
            addCriterion("test_time not in", values, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeBetween(Date value1, Date value2) {
            addCriterion("test_time between", value1, value2, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestTimeNotBetween(Date value1, Date value2) {
            addCriterion("test_time not between", value1, value2, "testTime");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdIsNull() {
            addCriterion("test_examination_id is null");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdIsNotNull() {
            addCriterion("test_examination_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdEqualTo(String value) {
            addCriterion("test_examination_id =", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotEqualTo(String value) {
            addCriterion("test_examination_id <>", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdGreaterThan(String value) {
            addCriterion("test_examination_id >", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_examination_id >=", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLessThan(String value) {
            addCriterion("test_examination_id <", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLessThanOrEqualTo(String value) {
            addCriterion("test_examination_id <=", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLike(String value) {
            addCriterion("test_examination_id like", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotLike(String value) {
            addCriterion("test_examination_id not like", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdIn(List<String> values) {
            addCriterion("test_examination_id in", values, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotIn(List<String> values) {
            addCriterion("test_examination_id not in", values, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdBetween(String value1, String value2) {
            addCriterion("test_examination_id between", value1, value2, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotBetween(String value1, String value2) {
            addCriterion("test_examination_id not between", value1, value2, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdIsNull() {
            addCriterion("test_problems_id is null");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdIsNotNull() {
            addCriterion("test_problems_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdEqualTo(String value) {
            addCriterion("test_problems_id =", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotEqualTo(String value) {
            addCriterion("test_problems_id <>", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdGreaterThan(String value) {
            addCriterion("test_problems_id >", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_problems_id >=", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLessThan(String value) {
            addCriterion("test_problems_id <", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLessThanOrEqualTo(String value) {
            addCriterion("test_problems_id <=", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLike(String value) {
            addCriterion("test_problems_id like", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotLike(String value) {
            addCriterion("test_problems_id not like", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdIn(List<String> values) {
            addCriterion("test_problems_id in", values, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotIn(List<String> values) {
            addCriterion("test_problems_id not in", values, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdBetween(String value1, String value2) {
            addCriterion("test_problems_id between", value1, value2, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotBetween(String value1, String value2) {
            addCriterion("test_problems_id not between", value1, value2, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestNumIsNull() {
            addCriterion("test_num is null");
            return (Criteria) this;
        }

        public Criteria andTestNumIsNotNull() {
            addCriterion("test_num is not null");
            return (Criteria) this;
        }

        public Criteria andTestNumEqualTo(Integer value) {
            addCriterion("test_num =", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumNotEqualTo(Integer value) {
            addCriterion("test_num <>", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumGreaterThan(Integer value) {
            addCriterion("test_num >", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_num >=", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumLessThan(Integer value) {
            addCriterion("test_num <", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumLessThanOrEqualTo(Integer value) {
            addCriterion("test_num <=", value, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumIn(List<Integer> values) {
            addCriterion("test_num in", values, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumNotIn(List<Integer> values) {
            addCriterion("test_num not in", values, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumBetween(Integer value1, Integer value2) {
            addCriterion("test_num between", value1, value2, "testNum");
            return (Criteria) this;
        }

        public Criteria andTestNumNotBetween(Integer value1, Integer value2) {
            addCriterion("test_num not between", value1, value2, "testNum");
            return (Criteria) this;
        }

        public Criteria andUserAnswerIsNull() {
            addCriterion("user_answer is null");
            return (Criteria) this;
        }

        public Criteria andUserAnswerIsNotNull() {
            addCriterion("user_answer is not null");
            return (Criteria) this;
        }

        public Criteria andUserAnswerEqualTo(String value) {
            addCriterion("user_answer =", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerNotEqualTo(String value) {
            addCriterion("user_answer <>", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerGreaterThan(String value) {
            addCriterion("user_answer >", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("user_answer >=", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerLessThan(String value) {
            addCriterion("user_answer <", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerLessThanOrEqualTo(String value) {
            addCriterion("user_answer <=", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerLike(String value) {
            addCriterion("user_answer like", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerNotLike(String value) {
            addCriterion("user_answer not like", value, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerIn(List<String> values) {
            addCriterion("user_answer in", values, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerNotIn(List<String> values) {
            addCriterion("user_answer not in", values, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerBetween(String value1, String value2) {
            addCriterion("user_answer between", value1, value2, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andUserAnswerNotBetween(String value1, String value2) {
            addCriterion("user_answer not between", value1, value2, "userAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIsNull() {
            addCriterion("right_answer is null");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIsNotNull() {
            addCriterion("right_answer is not null");
            return (Criteria) this;
        }

        public Criteria andRightAnswerEqualTo(String value) {
            addCriterion("right_answer =", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotEqualTo(String value) {
            addCriterion("right_answer <>", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerGreaterThan(String value) {
            addCriterion("right_answer >", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("right_answer >=", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLessThan(String value) {
            addCriterion("right_answer <", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLessThanOrEqualTo(String value) {
            addCriterion("right_answer <=", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerLike(String value) {
            addCriterion("right_answer like", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotLike(String value) {
            addCriterion("right_answer not like", value, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerIn(List<String> values) {
            addCriterion("right_answer in", values, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotIn(List<String> values) {
            addCriterion("right_answer not in", values, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerBetween(String value1, String value2) {
            addCriterion("right_answer between", value1, value2, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andRightAnswerNotBetween(String value1, String value2) {
            addCriterion("right_answer not between", value1, value2, "rightAnswer");
            return (Criteria) this;
        }

        public Criteria andIsRightIsNull() {
            addCriterion("is_right is null");
            return (Criteria) this;
        }

        public Criteria andIsRightIsNotNull() {
            addCriterion("is_right is not null");
            return (Criteria) this;
        }

        public Criteria andIsRightEqualTo(String value) {
            addCriterion("is_right =", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotEqualTo(String value) {
            addCriterion("is_right <>", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightGreaterThan(String value) {
            addCriterion("is_right >", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightGreaterThanOrEqualTo(String value) {
            addCriterion("is_right >=", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightLessThan(String value) {
            addCriterion("is_right <", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightLessThanOrEqualTo(String value) {
            addCriterion("is_right <=", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightLike(String value) {
            addCriterion("is_right like", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotLike(String value) {
            addCriterion("is_right not like", value, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightIn(List<String> values) {
            addCriterion("is_right in", values, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotIn(List<String> values) {
            addCriterion("is_right not in", values, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightBetween(String value1, String value2) {
            addCriterion("is_right between", value1, value2, "isRight");
            return (Criteria) this;
        }

        public Criteria andIsRightNotBetween(String value1, String value2) {
            addCriterion("is_right not between", value1, value2, "isRight");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_record
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_record
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}