package com.wangzefeng.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestExaminationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public TestExaminationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTestExaminationIdIsNull() {
            addCriterion("test_examination_id is null");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdIsNotNull() {
            addCriterion("test_examination_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdEqualTo(String value) {
            addCriterion("test_examination_id =", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotEqualTo(String value) {
            addCriterion("test_examination_id <>", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdGreaterThan(String value) {
            addCriterion("test_examination_id >", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_examination_id >=", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLessThan(String value) {
            addCriterion("test_examination_id <", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLessThanOrEqualTo(String value) {
            addCriterion("test_examination_id <=", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdLike(String value) {
            addCriterion("test_examination_id like", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotLike(String value) {
            addCriterion("test_examination_id not like", value, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdIn(List<String> values) {
            addCriterion("test_examination_id in", values, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotIn(List<String> values) {
            addCriterion("test_examination_id not in", values, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdBetween(String value1, String value2) {
            addCriterion("test_examination_id between", value1, value2, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andTestExaminationIdNotBetween(String value1, String value2) {
            addCriterion("test_examination_id not between", value1, value2, "testExaminationId");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterion("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterion("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterion("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterion("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterion("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterion("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterion("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIsNull() {
            addCriterion("test_type_id is null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIsNotNull() {
            addCriterion("test_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdEqualTo(String value) {
            addCriterion("test_type_id =", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotEqualTo(String value) {
            addCriterion("test_type_id <>", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThan(String value) {
            addCriterion("test_type_id >", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_type_id >=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThan(String value) {
            addCriterion("test_type_id <", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThanOrEqualTo(String value) {
            addCriterion("test_type_id <=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLike(String value) {
            addCriterion("test_type_id like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotLike(String value) {
            addCriterion("test_type_id not like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIn(List<String> values) {
            addCriterion("test_type_id in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotIn(List<String> values) {
            addCriterion("test_type_id not in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdBetween(String value1, String value2) {
            addCriterion("test_type_id between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotBetween(String value1, String value2) {
            addCriterion("test_type_id not between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestNumberIsNull() {
            addCriterion("test_number is null");
            return (Criteria) this;
        }

        public Criteria andTestNumberIsNotNull() {
            addCriterion("test_number is not null");
            return (Criteria) this;
        }

        public Criteria andTestNumberEqualTo(Integer value) {
            addCriterion("test_number =", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotEqualTo(Integer value) {
            addCriterion("test_number <>", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberGreaterThan(Integer value) {
            addCriterion("test_number >", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_number >=", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberLessThan(Integer value) {
            addCriterion("test_number <", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberLessThanOrEqualTo(Integer value) {
            addCriterion("test_number <=", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberIn(List<Integer> values) {
            addCriterion("test_number in", values, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotIn(List<Integer> values) {
            addCriterion("test_number not in", values, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberBetween(Integer value1, Integer value2) {
            addCriterion("test_number between", value1, value2, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("test_number not between", value1, value2, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestGradeIsNull() {
            addCriterion("test_grade is null");
            return (Criteria) this;
        }

        public Criteria andTestGradeIsNotNull() {
            addCriterion("test_grade is not null");
            return (Criteria) this;
        }

        public Criteria andTestGradeEqualTo(Integer value) {
            addCriterion("test_grade =", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeNotEqualTo(Integer value) {
            addCriterion("test_grade <>", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeGreaterThan(Integer value) {
            addCriterion("test_grade >", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_grade >=", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeLessThan(Integer value) {
            addCriterion("test_grade <", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeLessThanOrEqualTo(Integer value) {
            addCriterion("test_grade <=", value, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeIn(List<Integer> values) {
            addCriterion("test_grade in", values, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeNotIn(List<Integer> values) {
            addCriterion("test_grade not in", values, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeBetween(Integer value1, Integer value2) {
            addCriterion("test_grade between", value1, value2, "testGrade");
            return (Criteria) this;
        }

        public Criteria andTestGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("test_grade not between", value1, value2, "testGrade");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNull() {
            addCriterion("sys_user_id is null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIsNotNull() {
            addCriterion("sys_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysUserIdEqualTo(String value) {
            addCriterion("sys_user_id =", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotEqualTo(String value) {
            addCriterion("sys_user_id <>", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThan(String value) {
            addCriterion("sys_user_id >", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("sys_user_id >=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThan(String value) {
            addCriterion("sys_user_id <", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLessThanOrEqualTo(String value) {
            addCriterion("sys_user_id <=", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdLike(String value) {
            addCriterion("sys_user_id like", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotLike(String value) {
            addCriterion("sys_user_id not like", value, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdIn(List<String> values) {
            addCriterion("sys_user_id in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotIn(List<String> values) {
            addCriterion("sys_user_id not in", values, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdBetween(String value1, String value2) {
            addCriterion("sys_user_id between", value1, value2, "sysUserId");
            return (Criteria) this;
        }

        public Criteria andSysUserIdNotBetween(String value1, String value2) {
            addCriterion("sys_user_id not between", value1, value2, "sysUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_examination
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_examination
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}