package com.wangzefeng.example;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TestProblemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public TestProblemsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTestProblemsIdIsNull() {
            addCriterion("test_problems_id is null");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdIsNotNull() {
            addCriterion("test_problems_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdEqualTo(String value) {
            addCriterion("test_problems_id =", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotEqualTo(String value) {
            addCriterion("test_problems_id <>", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdGreaterThan(String value) {
            addCriterion("test_problems_id >", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_problems_id >=", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLessThan(String value) {
            addCriterion("test_problems_id <", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLessThanOrEqualTo(String value) {
            addCriterion("test_problems_id <=", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdLike(String value) {
            addCriterion("test_problems_id like", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotLike(String value) {
            addCriterion("test_problems_id not like", value, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdIn(List<String> values) {
            addCriterion("test_problems_id in", values, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotIn(List<String> values) {
            addCriterion("test_problems_id not in", values, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdBetween(String value1, String value2) {
            addCriterion("test_problems_id between", value1, value2, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestProblemsIdNotBetween(String value1, String value2) {
            addCriterion("test_problems_id not between", value1, value2, "testProblemsId");
            return (Criteria) this;
        }

        public Criteria andTestContentIsNull() {
            addCriterion("test_content is null");
            return (Criteria) this;
        }

        public Criteria andTestContentIsNotNull() {
            addCriterion("test_content is not null");
            return (Criteria) this;
        }

        public Criteria andTestContentEqualTo(String value) {
            addCriterion("test_content =", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentNotEqualTo(String value) {
            addCriterion("test_content <>", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentGreaterThan(String value) {
            addCriterion("test_content >", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentGreaterThanOrEqualTo(String value) {
            addCriterion("test_content >=", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentLessThan(String value) {
            addCriterion("test_content <", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentLessThanOrEqualTo(String value) {
            addCriterion("test_content <=", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentLike(String value) {
            addCriterion("test_content like", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentNotLike(String value) {
            addCriterion("test_content not like", value, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentIn(List<String> values) {
            addCriterion("test_content in", values, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentNotIn(List<String> values) {
            addCriterion("test_content not in", values, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentBetween(String value1, String value2) {
            addCriterion("test_content between", value1, value2, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestContentNotBetween(String value1, String value2) {
            addCriterion("test_content not between", value1, value2, "testContent");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIsNull() {
            addCriterion("test_type_id is null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIsNotNull() {
            addCriterion("test_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdEqualTo(String value) {
            addCriterion("test_type_id =", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotEqualTo(String value) {
            addCriterion("test_type_id <>", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThan(String value) {
            addCriterion("test_type_id >", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_type_id >=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThan(String value) {
            addCriterion("test_type_id <", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThanOrEqualTo(String value) {
            addCriterion("test_type_id <=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLike(String value) {
            addCriterion("test_type_id like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotLike(String value) {
            addCriterion("test_type_id not like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIn(List<String> values) {
            addCriterion("test_type_id in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotIn(List<String> values) {
            addCriterion("test_type_id not in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdBetween(String value1, String value2) {
            addCriterion("test_type_id between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotBetween(String value1, String value2) {
            addCriterion("test_type_id not between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestAnswerIsNull() {
            addCriterion("test_answer is null");
            return (Criteria) this;
        }

        public Criteria andTestAnswerIsNotNull() {
            addCriterion("test_answer is not null");
            return (Criteria) this;
        }

        public Criteria andTestAnswerEqualTo(String value) {
            addCriterion("test_answer =", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerNotEqualTo(String value) {
            addCriterion("test_answer <>", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerGreaterThan(String value) {
            addCriterion("test_answer >", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerGreaterThanOrEqualTo(String value) {
            addCriterion("test_answer >=", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerLessThan(String value) {
            addCriterion("test_answer <", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerLessThanOrEqualTo(String value) {
            addCriterion("test_answer <=", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerLike(String value) {
            addCriterion("test_answer like", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerNotLike(String value) {
            addCriterion("test_answer not like", value, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerIn(List<String> values) {
            addCriterion("test_answer in", values, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerNotIn(List<String> values) {
            addCriterion("test_answer not in", values, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerBetween(String value1, String value2) {
            addCriterion("test_answer between", value1, value2, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestAnswerNotBetween(String value1, String value2) {
            addCriterion("test_answer not between", value1, value2, "testAnswer");
            return (Criteria) this;
        }

        public Criteria andTestNumberIsNull() {
            addCriterion("test_number is null");
            return (Criteria) this;
        }

        public Criteria andTestNumberIsNotNull() {
            addCriterion("test_number is not null");
            return (Criteria) this;
        }

        public Criteria andTestNumberEqualTo(Integer value) {
            addCriterion("test_number =", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotEqualTo(Integer value) {
            addCriterion("test_number <>", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberGreaterThan(Integer value) {
            addCriterion("test_number >", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("test_number >=", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberLessThan(Integer value) {
            addCriterion("test_number <", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberLessThanOrEqualTo(Integer value) {
            addCriterion("test_number <=", value, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberIn(List<Integer> values) {
            addCriterion("test_number in", values, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotIn(List<Integer> values) {
            addCriterion("test_number not in", values, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberBetween(Integer value1, Integer value2) {
            addCriterion("test_number between", value1, value2, "testNumber");
            return (Criteria) this;
        }

        public Criteria andTestNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("test_number not between", value1, value2, "testNumber");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdIsNull() {
            addCriterion("propositional_user_id is null");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdIsNotNull() {
            addCriterion("propositional_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdEqualTo(String value) {
            addCriterion("propositional_user_id =", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdNotEqualTo(String value) {
            addCriterion("propositional_user_id <>", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdGreaterThan(String value) {
            addCriterion("propositional_user_id >", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("propositional_user_id >=", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdLessThan(String value) {
            addCriterion("propositional_user_id <", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdLessThanOrEqualTo(String value) {
            addCriterion("propositional_user_id <=", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdLike(String value) {
            addCriterion("propositional_user_id like", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdNotLike(String value) {
            addCriterion("propositional_user_id not like", value, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdIn(List<String> values) {
            addCriterion("propositional_user_id in", values, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdNotIn(List<String> values) {
            addCriterion("propositional_user_id not in", values, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdBetween(String value1, String value2) {
            addCriterion("propositional_user_id between", value1, value2, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalUserIdNotBetween(String value1, String value2) {
            addCriterion("propositional_user_id not between", value1, value2, "propositionalUserId");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateIsNull() {
            addCriterion("propositional_date is null");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateIsNotNull() {
            addCriterion("propositional_date is not null");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateEqualTo(Date value) {
            addCriterion("propositional_date =", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateNotEqualTo(Date value) {
            addCriterion("propositional_date <>", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateGreaterThan(Date value) {
            addCriterion("propositional_date >", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateGreaterThanOrEqualTo(Date value) {
            addCriterion("propositional_date >=", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateLessThan(Date value) {
            addCriterion("propositional_date <", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateLessThanOrEqualTo(Date value) {
            addCriterion("propositional_date <=", value, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateIn(List<Date> values) {
            addCriterion("propositional_date in", values, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateNotIn(List<Date> values) {
            addCriterion("propositional_date not in", values, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateBetween(Date value1, Date value2) {
            addCriterion("propositional_date between", value1, value2, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andPropositionalDateNotBetween(Date value1, Date value2) {
            addCriterion("propositional_date not between", value1, value2, "propositionalDate");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyIsNull() {
            addCriterion("degree_of_difficulty is null");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyIsNotNull() {
            addCriterion("degree_of_difficulty is not null");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyEqualTo(Integer value) {
            addCriterion("degree_of_difficulty =", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyNotEqualTo(Integer value) {
            addCriterion("degree_of_difficulty <>", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyGreaterThan(Integer value) {
            addCriterion("degree_of_difficulty >", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyGreaterThanOrEqualTo(Integer value) {
            addCriterion("degree_of_difficulty >=", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyLessThan(Integer value) {
            addCriterion("degree_of_difficulty <", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyLessThanOrEqualTo(Integer value) {
            addCriterion("degree_of_difficulty <=", value, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyIn(List<Integer> values) {
            addCriterion("degree_of_difficulty in", values, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyNotIn(List<Integer> values) {
            addCriterion("degree_of_difficulty not in", values, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyBetween(Integer value1, Integer value2) {
            addCriterion("degree_of_difficulty between", value1, value2, "degreeOfDifficulty");
            return (Criteria) this;
        }

        public Criteria andDegreeOfDifficultyNotBetween(Integer value1, Integer value2) {
            addCriterion("degree_of_difficulty not between", value1, value2, "degreeOfDifficulty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_problems
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_problems
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}