package com.wangzefeng.example;

import java.util.ArrayList;
import java.util.List;

public class TestTypeExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public TestTypeExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTestTypeIdIsNull() {
            addCriterion("test_type_id is null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIsNotNull() {
            addCriterion("test_type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdEqualTo(String value) {
            addCriterion("test_type_id =", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotEqualTo(String value) {
            addCriterion("test_type_id <>", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThan(String value) {
            addCriterion("test_type_id >", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdGreaterThanOrEqualTo(String value) {
            addCriterion("test_type_id >=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThan(String value) {
            addCriterion("test_type_id <", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLessThanOrEqualTo(String value) {
            addCriterion("test_type_id <=", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdLike(String value) {
            addCriterion("test_type_id like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotLike(String value) {
            addCriterion("test_type_id not like", value, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdIn(List<String> values) {
            addCriterion("test_type_id in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotIn(List<String> values) {
            addCriterion("test_type_id not in", values, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdBetween(String value1, String value2) {
            addCriterion("test_type_id between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestTypeIdNotBetween(String value1, String value2) {
            addCriterion("test_type_id not between", value1, value2, "testTypeId");
            return (Criteria) this;
        }

        public Criteria andTestNameIsNull() {
            addCriterion("test_name is null");
            return (Criteria) this;
        }

        public Criteria andTestNameIsNotNull() {
            addCriterion("test_name is not null");
            return (Criteria) this;
        }

        public Criteria andTestNameEqualTo(String value) {
            addCriterion("test_name =", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotEqualTo(String value) {
            addCriterion("test_name <>", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameGreaterThan(String value) {
            addCriterion("test_name >", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameGreaterThanOrEqualTo(String value) {
            addCriterion("test_name >=", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLessThan(String value) {
            addCriterion("test_name <", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLessThanOrEqualTo(String value) {
            addCriterion("test_name <=", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameLike(String value) {
            addCriterion("test_name like", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotLike(String value) {
            addCriterion("test_name not like", value, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameIn(List<String> values) {
            addCriterion("test_name in", values, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotIn(List<String> values) {
            addCriterion("test_name not in", values, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameBetween(String value1, String value2) {
            addCriterion("test_name between", value1, value2, "testName");
            return (Criteria) this;
        }

        public Criteria andTestNameNotBetween(String value1, String value2) {
            addCriterion("test_name not between", value1, value2, "testName");
            return (Criteria) this;
        }

        public Criteria andTestRemarkIsNull() {
            addCriterion("test_remark is null");
            return (Criteria) this;
        }

        public Criteria andTestRemarkIsNotNull() {
            addCriterion("test_remark is not null");
            return (Criteria) this;
        }

        public Criteria andTestRemarkEqualTo(String value) {
            addCriterion("test_remark =", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkNotEqualTo(String value) {
            addCriterion("test_remark <>", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkGreaterThan(String value) {
            addCriterion("test_remark >", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("test_remark >=", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkLessThan(String value) {
            addCriterion("test_remark <", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkLessThanOrEqualTo(String value) {
            addCriterion("test_remark <=", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkLike(String value) {
            addCriterion("test_remark like", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkNotLike(String value) {
            addCriterion("test_remark not like", value, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkIn(List<String> values) {
            addCriterion("test_remark in", values, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkNotIn(List<String> values) {
            addCriterion("test_remark not in", values, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkBetween(String value1, String value2) {
            addCriterion("test_remark between", value1, value2, "testRemark");
            return (Criteria) this;
        }

        public Criteria andTestRemarkNotBetween(String value1, String value2) {
            addCriterion("test_remark not between", value1, value2, "testRemark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_type
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table test_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}