package com.wangzefeng.pojo;

import java.util.Date;

public class AllFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.file_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.file_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.file_path
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.file_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.upload_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String uploadUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.upload_date
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Date uploadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column all_file.file_data_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String fileDataId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.file_id
     *
     * @return the value of all_file.file_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.file_id
     *
     * @param fileId the value for all_file.file_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.file_name
     *
     * @return the value of all_file.file_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.file_name
     *
     * @param fileName the value for all_file.file_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.file_path
     *
     * @return the value of all_file.file_path
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.file_path
     *
     * @param filePath the value for all_file.file_path
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.file_type
     *
     * @return the value of all_file.file_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.file_type
     *
     * @param fileType the value for all_file.file_type
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFileType(String fileType) {
        this.fileType = fileType == null ? null : fileType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.upload_user_id
     *
     * @return the value of all_file.upload_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUploadUserId() {
        return uploadUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.upload_user_id
     *
     * @param uploadUserId the value for all_file.upload_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUploadUserId(String uploadUserId) {
        this.uploadUserId = uploadUserId == null ? null : uploadUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.upload_date
     *
     * @return the value of all_file.upload_date
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getUploadDate() {
        return uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.upload_date
     *
     * @param uploadDate the value for all_file.upload_date
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUploadDate(Date uploadDate) {
        this.uploadDate = uploadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column all_file.file_data_id
     *
     * @return the value of all_file.file_data_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFileDataId() {
        return fileDataId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column all_file.file_data_id
     *
     * @param fileDataId the value for all_file.file_data_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFileDataId(String fileDataId) {
        this.fileDataId = fileDataId == null ? null : fileDataId.trim();
    }
}