package com.wangzefeng.pojo;

import org.springframework.format.annotation.DateTimeFormat;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String sysUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.full_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String fullName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_email
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_birthday
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_phone
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_photo
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.user_sign
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sys_user_id
     *
     * @return the value of sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sys_user_id
     *
     * @param sysUserId the value for sys_user.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_name
     *
     * @return the value of sys_user.user_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_name
     *
     * @param userName the value for sys_user.user_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.full_name
     *
     * @return the value of sys_user.full_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.full_name
     *
     * @param fullName the value for sys_user.full_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setFullName(String fullName) {
        this.fullName = fullName == null ? null : fullName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_email
     *
     * @return the value of sys_user.user_email
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_email
     *
     * @param userEmail the value for sys_user.user_email
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_birthday
     *
     * @return the value of sys_user.user_birthday
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_birthday
     *
     * @param userBirthday the value for sys_user.user_birthday
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_phone
     *
     * @return the value of sys_user.user_phone
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_phone
     *
     * @param userPhone the value for sys_user.user_phone
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserPhone(String userPhone) {
        this.userPhone = userPhone == null ? null : userPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_photo
     *
     * @return the value of sys_user.user_photo
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserPhoto() {
        return userPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_photo
     *
     * @param userPhoto the value for sys_user.user_photo
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserPhoto(String userPhoto) {
        this.userPhoto = userPhoto == null ? null : userPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.user_sign
     *
     * @return the value of sys_user.user_sign
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserSign() {
        return userSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.user_sign
     *
     * @param userSign the value for sys_user.user_sign
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserSign(String userSign) {
        this.userSign = userSign == null ? null : userSign.trim();
    }

    @Override
    public String toString() {
        return "SysUser{" +
                "sysUserId='" + sysUserId + '\'' +
                ", userName='" + userName + '\'' +
                ", password='" + password + '\'' +
                ", fullName='" + fullName + '\'' +
                ", userEmail='" + userEmail + '\'' +
                ", userBirthday=" + userBirthday +
                ", userPhone='" + userPhone + '\'' +
                ", userPhoto='" + userPhoto + '\'' +
                ", userSign='" + userSign + '\'' +
                '}';
    }
}