package com.wangzefeng.pojo;

public class TestProblemOption {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_problem_option.test_problem_option_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testProblemOptionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_problem_option.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testProblemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_problem_option.option_title
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String optionTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_problem_option.option_content
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String optionContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problem_option.test_problem_option_id
     *
     * @return the value of test_problem_option.test_problem_option_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestProblemOptionId() {
        return testProblemOptionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problem_option.test_problem_option_id
     *
     * @param testProblemOptionId the value for test_problem_option.test_problem_option_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestProblemOptionId(String testProblemOptionId) {
        this.testProblemOptionId = testProblemOptionId == null ? null : testProblemOptionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problem_option.test_problems_id
     *
     * @return the value of test_problem_option.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestProblemsId() {
        return testProblemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problem_option.test_problems_id
     *
     * @param testProblemsId the value for test_problem_option.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestProblemsId(String testProblemsId) {
        this.testProblemsId = testProblemsId == null ? null : testProblemsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problem_option.option_title
     *
     * @return the value of test_problem_option.option_title
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOptionTitle() {
        return optionTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problem_option.option_title
     *
     * @param optionTitle the value for test_problem_option.option_title
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOptionTitle(String optionTitle) {
        this.optionTitle = optionTitle == null ? null : optionTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problem_option.option_content
     *
     * @return the value of test_problem_option.option_content
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getOptionContent() {
        return optionContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problem_option.option_content
     *
     * @param optionContent the value for test_problem_option.option_content
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setOptionContent(String optionContent) {
        this.optionContent = optionContent == null ? null : optionContent.trim();
    }
}