package com.wangzefeng.pojo;

import java.util.Date;

public class TestProblems {

    private String testProblemsId;

    private String testContent;

    private String testTypeId;

    private String testAnswer;

    private Integer testNumber;

    private String propositionalUserId;

    private Date propositionalDate;

    private Integer degreeOfDifficulty;

    public String getTestProblemsId() {
        return testProblemsId;
    }


    public void setTestProblemsId(String testProblemsId) {
        this.testProblemsId = testProblemsId == null ? null : testProblemsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.test_content
     *
     * @return the value of test_problems.test_content
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestContent() {
        return testContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.test_content
     *
     * @param testContent the value for test_problems.test_content
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestContent(String testContent) {
        this.testContent = testContent == null ? null : testContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.test_type_id
     *
     * @return the value of test_problems.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestTypeId() {
        return testTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.test_type_id
     *
     * @param testTypeId the value for test_problems.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestTypeId(String testTypeId) {
        this.testTypeId = testTypeId == null ? null : testTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.test_answer
     *
     * @return the value of test_problems.test_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestAnswer() {
        return testAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.test_answer
     *
     * @param testAnswer the value for test_problems.test_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestAnswer(String testAnswer) {
        this.testAnswer = testAnswer == null ? null : testAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.test_number
     *
     * @return the value of test_problems.test_number
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Integer getTestNumber() {
        return testNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.test_number
     *
     * @param testNumber the value for test_problems.test_number
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestNumber(Integer testNumber) {
        this.testNumber = testNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.propositional_user_id
     *
     * @return the value of test_problems.propositional_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getPropositionalUserId() {
        return propositionalUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.propositional_user_id
     *
     * @param propositionalUserId the value for test_problems.propositional_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setPropositionalUserId(String propositionalUserId) {
        this.propositionalUserId = propositionalUserId == null ? null : propositionalUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.propositional_date
     *
     * @return the value of test_problems.propositional_date
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getPropositionalDate() {
        return propositionalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.propositional_date
     *
     * @param propositionalDate the value for test_problems.propositional_date
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setPropositionalDate(Date propositionalDate) {
        this.propositionalDate = propositionalDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_problems.degree_of_difficulty
     *
     * @return the value of test_problems.degree_of_difficulty
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Integer getDegreeOfDifficulty() {
        return degreeOfDifficulty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_problems.degree_of_difficulty
     *
     * @param degreeOfDifficulty the value for test_problems.degree_of_difficulty
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setDegreeOfDifficulty(Integer degreeOfDifficulty) {
        this.degreeOfDifficulty = degreeOfDifficulty;
    }
}