package com.wangzefeng.pojo;

public class TestType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_type.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_type.test_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_type.test_remark
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testRemark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_type.test_type_id
     *
     * @return the value of test_type.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestTypeId() {
        return testTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_type.test_type_id
     *
     * @param testTypeId the value for test_type.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestTypeId(String testTypeId) {
        this.testTypeId = testTypeId == null ? null : testTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_type.test_name
     *
     * @return the value of test_type.test_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestName() {
        return testName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_type.test_name
     *
     * @param testName the value for test_type.test_name
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestName(String testName) {
        this.testName = testName == null ? null : testName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_type.test_remark
     *
     * @return the value of test_type.test_remark
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestRemark() {
        return testRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_type.test_remark
     *
     * @param testRemark the value for test_type.test_remark
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestRemark(String testRemark) {
        this.testRemark = testRemark == null ? null : testRemark.trim();
    }
}