package com.wangzefeng.pojo;

import java.util.Date;

public class TestRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_record_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testRecordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Date testTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testExaminationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testProblemsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.test_num
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Integer testNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.user_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String userAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.right_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String rightAnswer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_record.is_right
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String isRight;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.test_record_id
     *
     * @return the value of test_record.test_record_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestRecordId() {
        return testRecordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.test_record_id
     *
     * @param testRecordId the value for test_record.test_record_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestRecordId(String testRecordId) {
        this.testRecordId = testRecordId == null ? null : testRecordId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.test_time
     *
     * @return the value of test_record.test_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getTestTime() {
        return testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.test_time
     *
     * @param testTime the value for test_record.test_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestTime(Date testTime) {
        this.testTime = testTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.test_examination_id
     *
     * @return the value of test_record.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestExaminationId() {
        return testExaminationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.test_examination_id
     *
     * @param testExaminationId the value for test_record.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestExaminationId(String testExaminationId) {
        this.testExaminationId = testExaminationId == null ? null : testExaminationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.test_problems_id
     *
     * @return the value of test_record.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestProblemsId() {
        return testProblemsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.test_problems_id
     *
     * @param testProblemsId the value for test_record.test_problems_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestProblemsId(String testProblemsId) {
        this.testProblemsId = testProblemsId == null ? null : testProblemsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.test_num
     *
     * @return the value of test_record.test_num
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Integer getTestNum() {
        return testNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.test_num
     *
     * @param testNum the value for test_record.test_num
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestNum(Integer testNum) {
        this.testNum = testNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.user_answer
     *
     * @return the value of test_record.user_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getUserAnswer() {
        return userAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.user_answer
     *
     * @param userAnswer the value for test_record.user_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setUserAnswer(String userAnswer) {
        this.userAnswer = userAnswer == null ? null : userAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.right_answer
     *
     * @return the value of test_record.right_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getRightAnswer() {
        return rightAnswer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.right_answer
     *
     * @param rightAnswer the value for test_record.right_answer
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setRightAnswer(String rightAnswer) {
        this.rightAnswer = rightAnswer == null ? null : rightAnswer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_record.is_right
     *
     * @return the value of test_record.is_right
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getIsRight() {
        return isRight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_record.is_right
     *
     * @param isRight the value for test_record.is_right
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setIsRight(String isRight) {
        this.isRight = isRight == null ? null : isRight.trim();
    }
}