package com.wangzefeng.pojo;

import java.util.Date;

public class TestExamination {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testExaminationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.start_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.end_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String testTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.test_number
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Integer testNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.test_grade
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private Integer testGrade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test_examination.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    private String sysUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.test_examination_id
     *
     * @return the value of test_examination.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestExaminationId() {
        return testExaminationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.test_examination_id
     *
     * @param testExaminationId the value for test_examination.test_examination_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestExaminationId(String testExaminationId) {
        this.testExaminationId = testExaminationId == null ? null : testExaminationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.start_time
     *
     * @return the value of test_examination.start_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.start_time
     *
     * @param startTime the value for test_examination.start_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.end_time
     *
     * @return the value of test_examination.end_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.end_time
     *
     * @param endTime the value for test_examination.end_time
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.test_type_id
     *
     * @return the value of test_examination.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getTestTypeId() {
        return testTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.test_type_id
     *
     * @param testTypeId the value for test_examination.test_type_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestTypeId(String testTypeId) {
        this.testTypeId = testTypeId == null ? null : testTypeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.test_number
     *
     * @return the value of test_examination.test_number
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Integer getTestNumber() {
        return testNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.test_number
     *
     * @param testNumber the value for test_examination.test_number
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestNumber(Integer testNumber) {
        this.testNumber = testNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.test_grade
     *
     * @return the value of test_examination.test_grade
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public Integer getTestGrade() {
        return testGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.test_grade
     *
     * @param testGrade the value for test_examination.test_grade
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setTestGrade(Integer testGrade) {
        this.testGrade = testGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test_examination.sys_user_id
     *
     * @return the value of test_examination.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public String getSysUserId() {
        return sysUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test_examination.sys_user_id
     *
     * @param sysUserId the value for test_examination.sys_user_id
     *
     * @mbggenerated Tue Jun 04 14:35:00 CST 2019
     */
    public void setSysUserId(String sysUserId) {
        this.sysUserId = sysUserId == null ? null : sysUserId.trim();
    }
}